const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const ADD_PERMISSION_ROOT = 'ADD_PERMISSION';
const ADD_PERMISSION_SUCCESS = 'ADD_PERMISSION_SUCCESS';
const ADD_PERMISSION_FAILURE = 'ADD_PERMISSION_FAILURE';
const ADD_PERMISSION_REQUEST = 'ADD_PERMISSION_REQUEST';
const REMOVE_PERMISSION_ROOT = 'REMOVE_PERMISSION';
const REMOVE_PERMISSION_REQUEST = 'REMOVE_PERMISSION_REQUEST';
const REMOVE_PERMISSION_FAILURE = 'REMOVE_PERMISSION_FAILURE';
const REMOVE_PERMISSION_SUCCESS = 'REMOVE_PERMISSION_SUCCESS';
const UPDATE_AVATAR_ROOT = 'UPDATE_AVATAR';
const FETCH_USERS_ROOT = 'FETCH_USERS';
const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE';
const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
const UPDATE_USER = 'UPDATE_USER';
const SET_NEXT = 'SET_NEXT';
const SET_ASSIGNED_NEXT = 'SET_ASSIGNED_NEXT';

export default {
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILURE,
  REMOVE_PERMISSION_REQUEST,
  REMOVE_PERMISSION_FAILURE,
  REMOVE_PERMISSION_SUCCESS,
  ADD_PERMISSION_SUCCESS,
  ADD_PERMISSION_FAILURE,
  ADD_PERMISSION_REQUEST,
  UPDATE_AVATAR_FAILURE,
  UPDATE_AVATAR_REQUEST,
  UPDATE_AVATAR_SUCCESS,
  FETCH_USERS_ROOT,
  REMOVE_PERMISSION_ROOT,
  ADD_PERMISSION_ROOT,
  FETCH_USERS_REQUEST,
  UPDATE_AVATAR_ROOT,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_FAILURE,
  UPDATE_USER,
  SET_NEXT,
  SET_ASSIGNED_NEXT,
};
