const FETCH_AVATARS_REQUEST = 'FETCH_AVATARS_REQUEST';
const FETCH_AVATARS_SUCCESS = 'FETCH_AVATARS_SUCCESS';
const FETCH_AVATARS_FAILURE = 'FETCH_AVATARS_FAILURE';

export default {
  FETCH_AVATARS_REQUEST,
  FETCH_AVATARS_SUCCESS,
  FETCH_AVATARS_FAILURE,
};
