const SEARCH_ASSIGNED_USERS_ROOT = 'SEARCH_ASSIGNED_USERS';
const SEARCH_USERS_ROOT = 'SEARCH_USERS';
const SEARCH_ASSIGNED_USERS_REQUEST = 'SEARCH_ASSIGNED_USERS_REQUEST';
const SEARCH_ASSIGNED_USERS_SUCCESS = 'SEARCH_ASSIGNED_USERS_SUCCESS';
const SEARCH_ASSIGNED_USERS_FAILURE = 'SEARCH_ASSIGNED_USERS_FAILURE';
const SEARCH_ASSIGNED_USERS_CANCELED = 'SEARCH_ASSIGNED_USERS_CANCELED';
const SEARCH_USERS_REQUEST = 'SEARCH_USERS_REQUEST';
const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';
const SEARCH_USERS_CANCELED = 'SEARCH_USERS_CANCELED';
const SEARCH_ASSIGNED_USERS_RESET = 'SEARCH_ASSIGNED_USERS_RESET';
const SEARCH_USERS_RESET = 'SEARCH_USERS_RESET';
const UPDATE_ASSIGNED_SEARCH = 'UPDATE_ASSIGNED_SEARCH';
const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
const REMOVE_FROM_ASSIGNED_SEARCH = 'REMOVE_FROM_ASSIGNED_SEARCH';
const REMOVE_FROM_USERS_SEARCH = 'REMOVE_FROM_USERS_SEARCH';

export default {
  SEARCH_ASSIGNED_USERS_ROOT,
  SEARCH_USERS_ROOT,
  UPDATE_ASSIGNED_SEARCH,
  UPDATE_USERS_SEARCH,
  REMOVE_FROM_ASSIGNED_SEARCH,
  REMOVE_FROM_USERS_SEARCH,
  SEARCH_ASSIGNED_USERS_REQUEST,
  SEARCH_ASSIGNED_USERS_SUCCESS,
  SEARCH_ASSIGNED_USERS_FAILURE,
  SEARCH_ASSIGNED_USERS_CANCELED,
  SEARCH_USERS_REQUEST,
  SEARCH_USERS_SUCCESS,
  SEARCH_USERS_FAILURE,
  SEARCH_USERS_CANCELED,
  SEARCH_ASSIGNED_USERS_RESET,
  SEARCH_USERS_RESET,
};
